### ISSUE TITLE
skyline freaked out

### ISSUE THREAD

**Issue by wannabefunniman** [skyline-dev/skyline#60]
![F7C2FBBE-259E-4069-92B0-52B6CF3C1998](https://user-images.githubusercontent.com/104086102/164261977-306d6294-3d99-4667-8200-e228eda8e47a.jpeg)
skyline freaked out and it told me to send a screenshot to you guys

**Comment by Coolsonickirby** [comment]
This is not a skyline issue. A plugin crashed.

**Comment by jam1garner** [comment]
You have a bad XMSBT mod enabled and this is an arcropolis crash, I recommend you report it on the discussion page of arcropolis: https://github.com/Raytwo/ARCropolis/discussions

If you want information to include you can quote the following:

Currently, invalid XMSBT files will result in a panic. Since the error type includes information on the error position it'd probably be preferable to give a human-readable error informing the user of what is going on and giving the relevant file path, line number, and column number.

**Comment by jam1garner** [comment]
I opened an issue for you as well: https://github.com/Raytwo/ARCropolis/issues/313. closing this one.
